"use strict";
const express=require("express");
const {Pool}=require("pg");
const bcrypt=require("bcryptjs");
const jwt=require("jsonwebtoken");
const crypto=require("crypto");

const app=express();
const PORT=Number(process.env.PORT||3000);
const DATABASE_URL=process.env.DATABASE_URL;
const JWT_SECRET=process.env.JWT_SECRET;
if(!DATABASE_URL){console.error("DATABASE_URL est obligatoire.");process.exit(1);}
if(!JWT_SECRET||JWT_SECRET.length<32){console.error("JWT_SECRET doit contenir au moins 32 caractères.");process.exit(1);}

const pool=new Pool({
  connectionString:DATABASE_URL,
  ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:undefined,
  max:10,connectionTimeoutMillis:10000,idleTimeoutMillis:30000
});

app.use(express.json({limit:"1mb"}));

// Vercel sert les fichiers statiques via son CDN.
// En local / hors Vercel, Express peut toujours servir index.html.
if (process.env.VERCEL !== "1") {
  app.use(express.static(__dirname,{extensions:["html"]}));
}
app.use((req,res,next)=>{
  res.header("Access-Control-Allow-Origin",process.env.FRONTEND_ORIGIN||"*");
  res.header("Access-Control-Allow-Headers","Origin, X-Requested-With, Content-Type, Accept, Authorization");
  res.header("Access-Control-Allow-Methods","GET, POST, PUT, PATCH, DELETE, OPTIONS");
  if(req.method==="OPTIONS")return res.sendStatus(204); next();
});

const SCHEMA=`
CREATE TABLE IF NOT EXISTS users(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 account_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,
 password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user' CHECK(role IN('user','admin')),
 status TEXT NOT NULL DEFAULT 'active' CHECK(status IN('active','blocked')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS wallets(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 cdf BIGINT NOT NULL DEFAULT 0 CHECK(cdf>=0),
 usd_cents BIGINT NOT NULL DEFAULT 0 CHECK(usd_cents>=0)
);
CREATE TABLE IF NOT EXISTS cards(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 card_number TEXT UNIQUE NOT NULL,expiry TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'active' CHECK(status IN('active','blocked'))
);
CREATE TABLE IF NOT EXISTS transactions(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 type TEXT NOT NULL,currency TEXT NOT NULL CHECK(currency IN('CDF','USD')),
 amount_cdf BIGINT NOT NULL DEFAULT 0,amount_usd_cents BIGINT NOT NULL DEFAULT 0,
 description TEXT,reference TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_account ON users(account_id);
CREATE INDEX IF NOT EXISTS idx_tx_user ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_tx_date ON transactions(created_at DESC);
`;

async function q(text,params=[],client=pool){return (await client.query(text,params)).rows}
async function user(id,client=pool){return (await q("SELECT * FROM users WHERE id=$1",[id],client))[0]||null}
async function wallet(id,client=pool){return (await q("SELECT * FROM wallets WHERE user_id=$1",[id],client))[0]||null}
async function card(id,client=pool){return (await q("SELECT * FROM cards WHERE user_id=$1",[id],client))[0]||null}
async function account(id,client=pool){
 const u=await user(id,client); if(!u)return null; const w=await wallet(id,client),c=await card(id,client);
 return {id:Number(u.id),account_id:u.account_id,name:u.name,email:u.email,role:u.role,status:u.status,created_at:u.created_at,
   wallet:{CDF:w?Number(w.cdf):0,USD:w?Number(w.usd_cents)/100:0},
   card:c?{id:Number(c.id),number:c.card_number,expiry:c.expiry,status:c.status}:null};
}
function aid(){return `DLZ-${new Date().getFullYear()}-${crypto.randomInt(100000,1000000)}`}
function cnum(){return [1,2,3,4].map(()=>crypto.randomInt(1000,10000)).join(" ")}
function expiry(){const d=new Date();d.setFullYear(d.getFullYear()+4);return `${String(d.getMonth()+1).padStart(2,"0")}/${String(d.getFullYear()).slice(-2)}`}
function ref(p="DLZ"){return `${p}-${Date.now()}-${crypto.randomBytes(4).toString("hex").toUpperCase()}`}
async function uniqueAccount(c){for(;;){const x=aid();if(!(await q("SELECT 1 FROM users WHERE account_id=$1",[x],c)).length)return x}}
async function uniqueCard(c){for(;;){const x=cnum();if(!(await q("SELECT 1 FROM cards WHERE card_number=$1",[x],c)).length)return x}}
async function tx(fn){const c=await pool.connect();try{await c.query("BEGIN");const r=await fn(c);await c.query("COMMIT");return r}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
function token(u){return jwt.sign({id:Number(u.id),role:u.role,account_id:u.account_id},JWT_SECRET,{expiresIn:"30d"})}
async function auth(req,res,next){
 const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({ok:false,message:"Authentification requise."});
 try{const d=jwt.verify(h.slice(7),JWT_SECRET),u=await user(d.id);if(!u)return res.status(401).json({ok:false,message:"Compte introuvable."});if(u.status!=="active")return res.status(403).json({ok:false,message:"Ce compte est bloqué."});req.user=u;next()}catch(e){res.status(401).json({ok:false,message:"Session invalide ou expirée."})}
}
function admin(req,res,next){if(req.user?.role!=="admin")return res.status(403).json({ok:false,message:"Accès administrateur refusé."});next()}
function name(v){return String(v||"").trim().replace(/\s+/g," ")}
function email(v){return String(v||"").trim().toLowerCase()}
function money(req){
 const currency=String(req.body.currency||"CDF").toUpperCase(),amount=Number(req.body.amount);
 return {currency,amount,amountCdf:currency==="CDF"?Math.round(amount):0,amountUsdCents:currency==="USD"?Math.round(amount*100):0}
}

app.get("/",(req,res)=>res.json({ok:true,name:"DALZON Wallet",version:"4.0.0",mode:"educational-simulation",database:"postgresql",message:"DALZON Wallet API opérationnelle."}));
app.get("/api/health",async(req,res)=>{try{await pool.query("SELECT 1");res.json({ok:true,service:"DALZON Wallet",version:"4.0.0",database:"connected",time:new Date().toISOString()})}catch(e){res.status(503).json({ok:false,database:"disconnected"})}});
app.get("/api/setup/status",async(req,res,next)=>{try{const a=await q("SELECT id FROM users WHERE role='admin' LIMIT 1");res.json({ok:true,adminExists:!!a.length,setupRequired:!a.length})}catch(e){next(e)}});

app.post("/api/setup/admin",async(req,res,next)=>{
 const n=name(req.body.name),e=email(req.body.email),p=String(req.body.password||"");
 if(n.length<2)return res.status(400).json({ok:false,message:"Le nom est invalide."});
 if(!e.includes("@"))return res.status(400).json({ok:false,message:"Adresse e-mail invalide."});
 if(p.length<8)return res.status(400).json({ok:false,message:"Le mot de passe doit contenir au moins 8 caractères."});
 try{
  const u=await tx(async c=>{
   if((await q("SELECT 1 FROM users WHERE role='admin' LIMIT 1",[],c)).length){const x=new Error("ADMIN_EXISTS");x.code="ADMIN_EXISTS";throw x}
   const h=await bcrypt.hash(p,12),a=await uniqueAccount(c);
   const u=(await q("INSERT INTO users(account_id,name,email,password_hash,role,status) VALUES($1,$2,$3,$4,'admin','active') RETURNING *",[a,n,e,h],c))[0];
   await q("INSERT INTO wallets(user_id) VALUES($1)",[u.id],c);await q("INSERT INTO cards(user_id,card_number,expiry) VALUES($1,$2,$3)",[u.id,await uniqueCard(c),expiry()],c);return u;
  });
  res.status(201).json({ok:true,message:"Administrateur créé avec succès.",token:token(u),user:await account(u.id)})
 }catch(x){if(x.code==="ADMIN_EXISTS")return res.status(409).json({ok:false,message:"Un administrateur existe déjà."});if(x.code==="23505")return res.status(409).json({ok:false,message:"Cette adresse e-mail est déjà utilisée."});next(x)}
});

app.post("/api/auth/login",async(req,res,next)=>{
 const id=String(req.body.identifier||req.body.email||req.body.account_id||"").trim().toLowerCase(),p=String(req.body.password||"");
 if(!id||!p)return res.status(400).json({ok:false,message:"Identifiants requis."});
 try{const u=(await q("SELECT * FROM users WHERE LOWER(email)=$1 OR LOWER(account_id)=$1 LIMIT 1",[id]))[0];
  if(!u||!(await bcrypt.compare(p,u.password_hash)))return res.status(401).json({ok:false,message:"Identifiants incorrects."});
  if(u.status!=="active")return res.status(403).json({ok:false,message:"Ce compte est bloqué."});
  res.json({ok:true,token:token(u),user:await account(u.id)})
 }catch(e){next(e)}
});

app.post("/api/auth/register",async(req,res,next)=>{
 const n=name(req.body.name),e=email(req.body.email),p=String(req.body.password||"");
 if(n.length<2)return res.status(400).json({ok:false,message:"Le nom est invalide."});
 if(!e.includes("@"))return res.status(400).json({ok:false,message:"Adresse e-mail invalide."});
 if(p.length<8)return res.status(400).json({ok:false,message:"Le mot de passe doit contenir au moins 8 caractères."});
 try{
  const u=await tx(async c=>{
   if((await q("SELECT 1 FROM users WHERE email=$1",[e],c)).length){const x=new Error("EMAIL_EXISTS");x.code="EMAIL_EXISTS";throw x}
   const h=await bcrypt.hash(p,12),a=await uniqueAccount(c);
   const u=(await q("INSERT INTO users(account_id,name,email,password_hash) VALUES($1,$2,$3,$4) RETURNING *",[a,n,e,h],c))[0];
   await q("INSERT INTO wallets(user_id) VALUES($1)",[u.id],c);await q("INSERT INTO cards(user_id,card_number,expiry) VALUES($1,$2,$3)",[u.id,await uniqueCard(c),expiry()],c);return u;
  });
  res.status(201).json({ok:true,message:"Compte créé avec succès.",token:token(u),user:await account(u.id)})
 }catch(x){if(x.code==="EMAIL_EXISTS"||x.code==="23505")return res.status(409).json({ok:false,message:"Cette adresse e-mail est déjà utilisée."});next(x)}
});

app.get("/api/account",auth,async(req,res,next)=>{try{const a=await account(req.user.id);if(!a)return res.status(404).json({ok:false,message:"Compte introuvable."});res.json({ok:true,user:a,account:a})}catch(e){next(e)}});
app.get("/api/transactions",auth,async(req,res,next)=>{try{const l=Math.min(Math.max(Number(req.query.limit)||50,1),100),rows=await q("SELECT id,type,currency,amount_cdf,amount_usd_cents,description,reference,created_at FROM transactions WHERE user_id=$1 ORDER BY id DESC LIMIT $2",[req.user.id,l]);res.json({ok:true,transactions:rows.map(x=>({...x,id:Number(x.id),amount_cdf:Number(x.amount_cdf),amount_usd_cents:Number(x.amount_usd_cents)}))})}catch(e){next(e)}});

app.post("/api/transfer",auth,async(req,res,next)=>{
 const m=money(req),to=String(req.body.recipient||req.body.account_id||req.body.accountId||"").trim().toLowerCase(),d=String(req.body.description||"Transfert DALZON Wallet").trim().slice(0,200);
 if(!to)return res.status(400).json({ok:false,message:"Destinataire requis."});if(!["CDF","USD"].includes(m.currency))return res.status(400).json({ok:false,message:"Devise invalide."});if(!Number.isFinite(m.amount)||m.amount<=0)return res.status(400).json({ok:false,message:"Montant invalide."});
 try{const r=await tx(async c=>{
  const u=(await q("SELECT * FROM users WHERE LOWER(email)=$1 OR LOWER(account_id)=$1 LIMIT 1 FOR UPDATE",[to],c))[0];
  if(!u){const x=new Error("NO_RECIPIENT");x.code="NO_RECIPIENT";throw x}if(Number(u.id)===Number(req.user.id)){const x=new Error("SELF");x.code="SELF";throw x}if(u.status!=="active"){const x=new Error("BLOCKED");x.code="BLOCKED";throw x}
  const sw=await wallet(req.user.id,c),rw=await wallet(u.id,c);if(!sw||!rw){const x=new Error("WALLET");x.code="WALLET";throw x}
  if(m.currency==="CDF"){if(Number(sw.cdf)<m.amountCdf){const x=new Error("FUNDS");x.code="FUNDS";throw x}await q("UPDATE wallets SET cdf=cdf-$1 WHERE user_id=$2",[m.amountCdf,req.user.id],c);await q("UPDATE wallets SET cdf=cdf+$1 WHERE user_id=$2",[m.amountCdf,u.id],c)}
  else{if(Number(sw.usd_cents)<m.amountUsdCents){const x=new Error("FUNDS");x.code="FUNDS";throw x}await q("UPDATE wallets SET usd_cents=usd_cents-$1 WHERE user_id=$2",[m.amountUsdCents,req.user.id],c);await q("UPDATE wallets SET usd_cents=usd_cents+$1 WHERE user_id=$2",[m.amountUsdCents,u.id],c)}
  const rr=ref("TRF");await q("INSERT INTO transactions(user_id,type,currency,amount_cdf,amount_usd_cents,description,reference) VALUES($1,'transfer',$2,$3,$4,$5,$6)",[req.user.id,m.currency,m.amountCdf,m.amountUsdCents,d,rr],c);await q("INSERT INTO transactions(user_id,type,currency,amount_cdf,amount_usd_cents,description,reference) VALUES($1,'receive',$2,$3,$4,$5,$6)",[u.id,m.currency,m.amountCdf,m.amountUsdCents,d,rr],c);return rr
 });res.json({ok:true,message:"Transfert effectué.",reference:r})
 }catch(x){if(x.code==="NO_RECIPIENT")return res.status(404).json({ok:false,message:"Destinataire introuvable."});if(x.code==="SELF")return res.status(400).json({ok:false,message:"Vous ne pouvez pas vous transférer de l'argent à vous-même."});if(x.code==="BLOCKED")return res.status(403).json({ok:false,message:"Le compte destinataire est bloqué."});if(x.code==="FUNDS")return res.status(400).json({ok:false,message:"Solde insuffisant."});next(x)}
});

app.post("/api/payment",auth,async(req,res,next)=>{
 const m=money(req),merchant=String(req.body.merchant||req.body.description||"Paiement simulé").trim().slice(0,200);
 if(!["CDF","USD"].includes(m.currency)||!Number.isFinite(m.amount)||m.amount<=0)return res.status(400).json({ok:false,message:"Montant ou devise invalide."});
 try{const r=await tx(async c=>{const w=await wallet(req.user.id,c);if(!w){const x=new Error("WALLET");x.code="WALLET";throw x}
  if(m.currency==="CDF"){if(Number(w.cdf)<m.amountCdf){const x=new Error("FUNDS");x.code="FUNDS";throw x}await q("UPDATE wallets SET cdf=cdf-$1 WHERE user_id=$2",[m.amountCdf,req.user.id],c)}
  else{if(Number(w.usd_cents)<m.amountUsdCents){const x=new Error("FUNDS");x.code="FUNDS";throw x}await q("UPDATE wallets SET usd_cents=usd_cents-$1 WHERE user_id=$2",[m.amountUsdCents,req.user.id],c)}
  const rr=ref("PAY");await q("INSERT INTO transactions(user_id,type,currency,amount_cdf,amount_usd_cents,description,reference) VALUES($1,'payment',$2,$3,$4,$5,$6)",[req.user.id,m.currency,m.amountCdf,m.amountUsdCents,merchant,rr],c);return rr
 });res.json({ok:true,message:"Paiement simulé effectué.",reference:r})}catch(x){if(x.code==="FUNDS")return res.status(400).json({ok:false,message:"Solde insuffisant."});next(x)}
});

app.get("/api/admin/dashboard",auth,admin,async(req,res,next)=>{try{
 const a=await Promise.all([
  q("SELECT COUNT(*) n FROM users WHERE role='user'"),q("SELECT COUNT(*) n FROM users WHERE role='user' AND status='active'"),q("SELECT COUNT(*) n FROM users WHERE role='user' AND status='blocked'"),q("SELECT COUNT(*) n FROM transactions"),q("SELECT COALESCE(SUM(cdf),0) n FROM wallets"),q("SELECT COALESCE(SUM(usd_cents),0) n FROM wallets")
 ]);res.json({ok:true,stats:{totalUsers:Number(a[0][0].n),activeUsers:Number(a[1][0].n),blockedUsers:Number(a[2][0].n),totalTransactions:Number(a[3][0].n),totalCdf:Number(a[4][0].n),totalUsd:Number(a[5][0].n)/100}})
}catch(e){next(e)}});

app.get("/api/admin/users",auth,admin,async(req,res,next)=>{try{const rows=await q("SELECT u.id,u.account_id,u.name,u.email,u.role,u.status,u.created_at,COALESCE(w.cdf,0)cdf,COALESCE(w.usd_cents,0)usd_cents FROM users u LEFT JOIN wallets w ON w.user_id=u.id ORDER BY u.id DESC");res.json({ok:true,users:rows.map(u=>({id:Number(u.id),account_id:u.account_id,name:u.name,email:u.email,role:u.role,status:u.status,created_at:u.created_at,wallet:{CDF:Number(u.cdf),USD:Number(u.usd_cents)/100}}))})}catch(e){next(e)}});

app.post("/api/admin/credit",auth,admin,async(req,res,next)=>{
 const id=Number(req.body.userId||req.body.user_id),m=money(req),d=String(req.body.description||"Crédit administrateur").trim().slice(0,200);
 if(!Number.isInteger(id)||id<=0||!["CDF","USD"].includes(m.currency)||!Number.isFinite(m.amount)||m.amount<=0)return res.status(400).json({ok:false,message:"Données invalides."});
 try{const r=await tx(async c=>{if(!await user(id,c)){const x=new Error("NO_USER");x.code="NO_USER";throw x}if(m.currency==="CDF")await q("UPDATE wallets SET cdf=cdf+$1 WHERE user_id=$2",[m.amountCdf,id],c);else await q("UPDATE wallets SET usd_cents=usd_cents+$1 WHERE user_id=$2",[m.amountUsdCents,id],c);const rr=ref("ADM");await q("INSERT INTO transactions(user_id,type,currency,amount_cdf,amount_usd_cents,description,reference) VALUES($1,'credit',$2,$3,$4,$5,$6)",[id,m.currency,m.amountCdf,m.amountUsdCents,d,rr],c);return rr});res.json({ok:true,message:"Solde ajouté avec succès.",reference:r})}catch(x){if(x.code==="NO_USER")return res.status(404).json({ok:false,message:"Utilisateur introuvable."});next(x)}
});

async function status(req,res,next,s,msg){const id=Number(req.body.userId||req.body.user_id);if(!Number.isInteger(id)||id<=0)return res.status(400).json({ok:false,message:"Utilisateur invalide."});try{const u=await user(id);if(!u)return res.status(404).json({ok:false,message:"Utilisateur introuvable."});if(u.role==="admin")return res.status(403).json({ok:false,message:"Le compte administrateur ne peut pas être bloqué depuis cette interface."});await pool.query("UPDATE users SET status=$1 WHERE id=$2",[s,id]);res.json({ok:true,message:msg})}catch(e){next(e)}}
app.post("/api/admin/block",auth,admin,(req,res,next)=>status(req,res,next,"blocked","Compte bloqué."));
app.post("/api/admin/unblock",auth,admin,(req,res,next)=>status(req,res,next,"active","Compte débloqué."));
app.get("/api/admin/users/:id",auth,admin,async(req,res,next)=>{try{const u=await account(Number(req.params.id));if(!u)return res.status(404).json({ok:false,message:"Utilisateur introuvable."});res.json({ok:true,user:u})}catch(e){next(e)}});
app.get("/api/admin/transactions",auth,admin,async(req,res,next)=>{try{const l=Math.min(Math.max(Number(req.query.limit)||100,1),500),rows=await q("SELECT t.id,t.user_id,t.type,t.currency,t.amount_cdf,t.amount_usd_cents,t.description,t.reference,t.created_at,u.account_id,u.name,u.email FROM transactions t JOIN users u ON u.id=t.user_id ORDER BY t.id DESC LIMIT $1",[l]);res.json({ok:true,transactions:rows.map(t=>({...t,id:Number(t.id),user_id:Number(t.user_id),amount_cdf:Number(t.amount_cdf),amount_usd_cents:Number(t.amount_usd_cents)}))})}catch(e){next(e)}});
app.post("/api/auth/logout",auth,(req,res)=>res.json({ok:true,message:"Déconnexion effectuée."}));

app.use((req,res)=>res.status(404).json({ok:false,message:"Route introuvable."}));
app.use((err,req,res,next)=>{console.error("DALZON API ERROR:",err);if(res.headersSent)return next(err);res.status(500).json({ok:false,message:"Erreur interne du serveur."})});

async function start(){await pool.query(SCHEMA);app.listen(PORT,"0.0.0.0",()=>console.log(`DALZON Wallet API PostgreSQL sur ${PORT}`))}
process.on("SIGTERM",async()=>{await pool.end();process.exit(0)});process.on("SIGINT",async()=>{await pool.end();process.exit(0)});
start().catch(e=>{console.error("Démarrage impossible:",e);process.exit(1)});
